import fs from "node:fs";
const worker=fs.readFileSync("apps/worker/src/worker.ts","utf8");
const web=fs.readFileSync("apps/web/src/App.tsx","utf8");
const must=(ok,msg)=>{if(!ok){console.error(`[FAIL] ${msg}`);process.exit(1)}console.log(`[PASS] ${msg}`)};
console.log("[ROUND 1] clean execution path");
const scheduler=worker.slice(worker.indexOf("async function schedulerTick"), worker.indexOf("const adminplusConfig", worker.indexOf("async function schedulerTick")));
must(scheduler.includes("runR10CouponScheduler"),"R10 is scheduled coupon path");
must(!scheduler.includes("processDueCouponRetries"),"legacy retry processor removed from scheduler");
must(!scheduler.includes("applyOneAutomationTemplate"),"legacy applyOne removed from scheduler");
must(worker.includes('COUPON_R10_REVISION = "v249-r10-clean-coupon-engine-20260816"'),"R10 runtime marker");
console.log("[ROUND 2] vendorItem truth / atomic claim");
must(worker.includes("r10VendorItemIds") && worker.includes("option.vendorItemId") && worker.includes("option.optionId"),"explicit vendorItemId normalization with legacy migration fallback");
must(worker.includes('retry_key: retryKey') && worker.includes('status: "running"') && worker.includes('code === "23505"'),"atomic unique claim");
must(worker.includes("r10ClaimSlot") && worker.includes("Math.floor(minute / 5)"),"five-minute claim slot");
console.log("[ROUND 3] create attach verify cleanup");
must(worker.includes("r10CreatePayload") && worker.includes('coupon create requestedId missing'),"single create state");
must(worker.includes('{ vendorItems: vendorItemIds }'),"attach uses verified vendorItemIds");
must(worker.includes("verifyCouponItemsActuallyApplied(env, couponId, vendorItemIds"),"actual APPLIED item verification");
must(worker.includes("findActuallyAppliedCouponByPayload(env, payload"),"actual payload snapshot verification");
must(worker.includes("r10CancelCouponAndVerify") && worker.includes("cleanup pending and reissue blocked"),"failed generated coupon cleanup gate");
console.log("[ROUND 4] schedule / regressions / UI");
must(worker.includes('timeToMinutes("23:52")') && worker.includes('timeToMinutes("01:00")'),"23:52 to 01:00 repair window");
must(worker.includes('23:50:00'),"fixed 23:50 end anchor");
must(worker.includes("adminplusMultiAccountFlowRevision"),"AdminPlus R9.2 retained");
must(worker.includes("manualOrderSafeRelinkRevision"),"shipment R7.1 retained");
must(worker.includes("tossPaidCollectionRevision"),"Toss collection retained");
must(web.includes('UI_RELEASE_REVISION = "V249 R10"'),"V249 R10 UI marker");
console.log("[PASS] V249 R10 clean coupon engine verification completed (4 rounds).");
