import fs from "node:fs";
const worker=fs.readFileSync(new URL("../apps/worker/src/worker.ts", import.meta.url),"utf8");
const app=fs.readFileSync(new URL("../apps/web/src/App.tsx", import.meta.url),"utf8");
let fail=0; const must=(v,m)=>{console.log(`${v?'[PASS]':'[FAIL]'} ${m}`); if(!v) fail++;};
console.log('[ROUND 1] AdminPlus create response reconciliation');
must(worker.includes('adminplusCreateResponseMatch') && worker.includes('adminplusDeepObjects'), 'create response accepts nested/wrapped order shapes');
must(worker.includes('adminplusCustomerCodeFromObject') && worker.includes('customerOrderCode'), 'customer_order_code is resolved from order or product level');
must(worker.includes('adminplusRecoverCreatedOrder') && worker.includes('[0, 700, 1800]'), 'created order is reconciled with delayed customer-code lookup');
console.log('[ROUND 2] safe batch fallback');
must(worker.includes('if (result && !result.ok)') && worker.includes('{ orders: [orderPayload] }'), 'failed batch retries only unresolved rows individually');
must(worker.includes('성공 응답인데 구조만 미확인인 경우에는 중복 생성을 피하기 위해 재POST하지 않습니다'), 'successful-but-unconfirmed batch is never blindly re-posted');
must(worker.includes('createdKeys.has(row.sourceKey) || historyKeys.has(row.sourceKey)'), 'existing duplicate guard remains');
console.log('[ROUND 3] operator diagnostics/regression');
must(worker.includes('adminplusOrderRecoveryRevision: "adminplus-create-reconcile-v223-20260809"'), 'V223 recovery revision exposed');
must(app.includes('executionErrors') && app.includes('실행오류'), 'UI surfaces concrete purchase execution errors');
must(worker.includes('toss-paid-collection-v221-20260809') && worker.includes('manual-backlog-server-source-v222-20260809'), 'V221/V222 fixes retained');
if(fail){console.error(`[FAIL] V223 verification failed: ${fail}`);process.exit(1);} console.log('[PASS] V223 AdminPlus create/reconcile verification completed (3 rounds).');
