import fs from "node:fs";
const app=fs.readFileSync("apps/web/src/App.tsx","utf8");
const must=(ok,msg)=>{if(!ok)throw new Error(msg);console.log(`[PASS] ${msg}`)};
console.log("[ROUND 1] mapping JSX structure");
must(!app.includes("</table>\n          </div>\n          </div>\n        </section>"),"duplicate closing div removed");
must(app.includes("</table>\n          </div>\n        </section>\n      )}"),"mapping table closes table-wrap then panel section");
console.log("[ROUND 2] Excel UI retained");
must(app.includes('className="mapping-master-table"'),"Excel-schema mapping table retained");
must(app.includes("<th>채널</th><th>옵션ID</th><th>업체명</th><th>코드번호</th><th>업체상품명</th>"),"Excel mapping header retained");
console.log("[ROUND 3] V235 release retained");
must(app.includes('EXCEL_SCHEMA_UI_REVISION = "v235-excel-schema-ui-catalog-review-20260811"'),"V235 UI revision retained");
console.log("[PASS] V235 R1 mapping JSX structure verification completed (3 rounds).");
