import fs from "fs";
const read=(p)=>fs.readFileSync(p,"utf8");
const must=(cond,name)=>{ if(!cond){ console.error("[FAIL]",name); process.exitCode=1; } else console.log("[PASS]",name); };
const app=read("apps/web/src/App.tsx");
const css=read("apps/web/src/style.css");
const worker=read("apps/worker/src/worker.ts");
const http=read("apps/worker/src/lib/http.ts");
const pkg=JSON.parse(read("package.json"));
const wpkg=JSON.parse(read("apps/worker/package.json"));
const workflow=read(".github/workflows/cloudflare-worker-deploy.yml");
console.log("[ROUND 1] free-tier I/O");
must(worker.includes('FREE_TIER_CLEANUP_REVISION = "v258-free-tier-cleanup-ui-20260817"'),"V258 worker marker");
must(worker.includes('.select("settings_key,updated_at")'),"scheduler polls lightweight settings metadata");
must(worker.includes('schedulerPayloadCache?.settingsKey'),"scheduler reuses unchanged payload");
must(worker.includes('kstTimeText() === "03:20"') && !/try\s*\{\s*await cleanupR2ExpiredFiles\(env\);/.test(worker),"R2 cleanup reduced to daily scan");
must(http.includes('JSON.stringify(data)') && !http.includes('JSON.stringify(data, null, 2)'),"API JSON compact output");
console.log("[ROUND 2] dead code/dependency cleanup");
for(const name of ["processDueCouponRetries","retryImmediate","couponAdaptiveHealthCheckDue","withCoupangSingleDateQuery"]) must(!worker.includes('function '+name+'('),name+" removed");
for(const name of ["optionPurchaseTimeIncludes","buildImmediateRollingTemplateRows","SHIPMENT_INPUT_ALIASES"]) must(!app.includes(name),name+" removed");
must(!("zod" in (wpkg.dependencies||{})),"unused zod removed");
must(!("@types/node" in (wpkg.devDependencies||{})),"direct unused @types/node removed");
console.log("[ROUND 3] deployment economy");
must(workflow.includes('paths:') && workflow.includes('apps/worker/**'),"Worker deploy path filter");
must(!workflow.includes('apps/web/**'),"web-only changes do not deploy Worker");
must(workflow.includes('cancel-in-progress: true'),"superseded Worker deploy canceled");
console.log("[ROUND 4] UI alignment");
must(app.includes('const UI_RELEASE_REVISION = "V258"'),"V258 UI header");
must(app.includes('FREE_TIER_CLEANUP_REVISION = "v258-free-tier-cleanup-ui-20260817"'),"V258 web marker");
must(css.includes('V258: consistent control alignment'),"alignment normalization CSS");
must(css.includes('--control-height: 40px') && css.includes('--table-control-height: 34px'),"consistent control heights");
must(css.includes('api-overview-inline-controls'),"today range remains horizontal");
must(css.includes('V258 R1: screenshot-based desktop alignment'),"V258 R1 screenshot alignment marker");
must(css.includes('workspace-subtabs') && css.includes('repeat(5, minmax(0, 1fr))'),"mapping workspace tabs align in one desktop row");
must(css.includes('.coupon-new-actions') && css.includes('repeat(3, minmax(0, 1fr))'),"coupon step-one actions use three equal columns");
must(app.includes('credential-grid credential-grid-single') && app.includes('credential-grid credential-grid-two'),"settings credential field counts align");
must(app.includes('order-flow-range-toolbar') && css.includes('.order-flow-range-toolbar'),"automation flow range toolbar aligns by five columns");
must(css.includes('V258 R2: mapping row compact column alignment'),"V258 R2 mapping-row alignment marker");
must(css.includes('th:nth-child(2) { width:100px; }') && css.includes('.mapping-option-input { width:100%; min-width:0; }'),"mapping option ID column reduced by about 25 percent");
must(css.includes('th:nth-child(8) { width:70px; }') && css.includes('.mapping-price-input { width:70px; min-width:64px; }'),"mapping unit-cost column reduced by about 25 percent");
must(css.includes('th:nth-child(10) { width:86px; }') && css.includes('.mapping-time-input { width:86px; min-width:82px; }'),"mapping purchase-time column reduced by about 40 percent");
must(app.includes('service-status-pill mapping-vendor-status') && css.includes('background:transparent'),"mapping API status uses plain text without badge background");
must(css.includes('td:nth-child(5) { padding-right:2px; }') && css.includes('td:nth-child(6) { padding-left:2px; }'),"product-to-base-qty gap normalized");
must(css.includes('td:nth-child(9) { padding-right:4px; }') && css.includes('td:nth-child(10) { padding-left:4px; }'),"configured-cost-to-purchase-time gap normalized");
console.log("[ROUND 5] regression anchors");
must(app.includes('v257-status-range-count-fix-20260817'),"V257 status-range retained");
must(app.includes('v256-manual-mapping-nonapi-transition-20260817'),"V256 manual mapping retained");
must(worker.includes('v255-adminplus-link-status-fix-20260817'),"V255 AdminPlus source truth retained");
must(worker.includes('COUPON_R10_REVISION'),"coupon R10 retained");
must(pkg.scripts["verify:all"].includes("verify:v258"),"verify all includes V258");
if(process.exitCode) process.exit(process.exitCode);
console.log("\n[PASS] V258 free-tier cleanup/UI alignment verification completed (5 rounds).");
