import fs from "node:fs";
const worker = fs.readFileSync(new URL("../apps/worker/src/worker.ts", import.meta.url), "utf8");
const app = fs.readFileSync(new URL("../apps/web/src/App.tsx", import.meta.url), "utf8");
const must=(ok,msg)=>{ if(!ok){console.error(`[FAIL] ${msg}`); process.exit(1);} console.log(`[PASS] ${msg}`); };
console.log("[ROUND 1] designated shipment schedule policy");
must(worker.includes('ADMINPLUS_SHIPMENT_DEFAULT_TIMES = ["14:00", "18:00", "23:00"]'), "Ncloud/Worker default shipment slots are 14:00,18:00,23:00");
must(worker.includes('filter((time) => time !== "10:00")'), "legacy 10:00 shipment slot is removed");
must(worker.includes('migrated.includes("23:00")'), "23:00 shipment slot is guaranteed");
must(app.includes('shipmentTimes: ["14:00", "18:00", "23:00"]'), "web default shipment slots match runtime");
must(app.includes('placeholder="14:00, 18:00, 23:00"'), "operator UI shows new designated schedule");
console.log("[ROUND 2] shipment recovery coverage");
must(worker.includes('"invoiceCompany"') && worker.includes('"deliveryInvoiceNo"'), "AdminPlus invoice-style courier/tracking aliases are parsed");
must(worker.includes('"shipmentNumber"') && worker.includes('"shippingTrackingNumber"'), "additional shipment tracking aliases are parsed");
must(worker.includes('deepTrackingHint'), "tracking-incomplete diagnostics expose deep parsed hints");
must(worker.includes('adminplusFindOrderForHistory') && worker.includes('recent_orders_scan'), "direct/recent-order recovery remains active");
console.log("[ROUND 3] regression / revision");
must(worker.includes('v248-r4-scheduled-shipment-recovery-fix-20260812'), "V248 R4 runtime marker exposed");
must(worker.includes('v248-r3-adminplus-orderer-parity-fix-20260812'), "V248 R3 orderer fix retained");
must(worker.includes('v248-r2-adminplus-virtual-phone-fix-20260812'), "V248 R2 virtual-phone fix retained");
must(/const UI_RELEASE_REVISION = \"V248 R\d+(?:\.\d+)?\";/.test(app), "UI release follows current V248 R5+ release");
console.log("[PASS] V248 R4 scheduled-shipment recovery verification completed (3 rounds).");
