import fs from "node:fs";
const worker=fs.readFileSync("apps/worker/src/worker.ts","utf8");
const must=(ok,msg)=>{if(!ok) throw new Error(msg); console.log(`[PASS] ${msg}`)};
console.log("[ROUND 1] Excel/option mapping policy");
must(worker.includes("normalizeOptionPurchaseTimeList"), "option purchase-time normalization retained");
must(worker.includes("최신 엑셀 상품과 현재 서버 확정상품이 다릅니다."), "latest Excel mismatch requires reconfirm instead of soldout");
must(worker.includes("상품 변경 시 이전 상품 옵션은 재사용할 수 없습니다."), "old optionCode cannot leak after product change");
must(worker.includes("toss-stock-productitem-v219-20260809"), "Toss stockId/productItemId bridge retained");
console.log("[ROUND 2] payment/price/shipment safety");
must(worker.includes("adminplus-payment-policy-guard-v224-20260809"), "payment policy guard retained");
must(worker.includes("v240-active-first-false-soldout-fix-20260811"), "active-first false-soldout guard retained");
must(worker.includes("v241-pricewatch-account-routing-fix-20260811"), "current vendor account routing retained");
must(worker.includes("v242-order-container-tracking-recovery-20260811"), "shipment order-container recovery retained");
must(worker.includes("v243-r1-typescript-fix-20260811"), "shipment TypeScript hotfix retained");
console.log("[ROUND 3] current revision + no known regressions");
must(worker.includes("v246-current-policy-verifier-alignment-20260812"), "V246 current-policy marker exposed");
must(!worker.includes("scanned: found.scanned || 0"), "unsafe shipment union access remains removed");
must(worker.includes("for (const value of shipmentRows)") && worker.includes("const row = objectRecord(value);"), "generic shipment row normalization retained");
console.log("[PASS] V246 current-policy regression guard completed (3 rounds).");
