import fs from "node:fs";
const app=fs.readFileSync("apps/web/src/App.tsx","utf8");
const worker=fs.readFileSync("apps/worker/src/worker.ts","utf8");
const pkg=JSON.parse(fs.readFileSync("package.json","utf8"));
let failed=0;
function check(name,cond){ if(cond) console.log(`[PASS] ${name}`); else {console.error(`[FAIL] ${name}`); failed++;} }
console.log("[ROUND 1] release/version truth");
check(/const\s+UI_RELEASE_REVISION\s*=\s*["\']V(?:25[4-9]|2[6-9]\d|[3-9]\d\d)[^"\']*["\']/.test(app), "V254 header version");
check("V254 web marker", app.includes('v254-adminplus-source-of-truth-20260817'));
check("V254 worker marker", worker.includes('v254-adminplus-source-of-truth-20260817'));
check(/0\.1\.0-v(?:25[4-9]|2[6-9]\d|[3-9]\d\d)[^"\s]*/.test(pkg), "package release updated");
check("verify all includes V253 and V254", String(pkg.scripts?.["verify:all"]||"").includes("verify:v253") && String(pkg.scripts?.["verify:all"]||"").includes("verify:v254"));
console.log("[ROUND 2] AdminPlus actual order status source-of-truth");
check("history stores actual AdminPlus status", app.includes("adminplusStatus?: string") && worker.includes("adminplusStatus?: string"));
check("actual status reconciliation scans AdminPlus orders", worker.includes("adminplusReconcileCurrentOrderStatuses") && worker.includes('GET", "/v1/seller/orders"'));
check("purchase status endpoint reconciles actual status", worker.includes("adminplusStatusMatched:orderStatuses.matched") && worker.includes('mode:"adminplus_purchase_status_v254_actual_order_state"'));
check("flow status uses actual AdminPlus status first", app.includes("adminPlusFlowStatusFromActualStatus(row.adminplusStatus)"));
check("marketplacePreparingAt removed from flow decision", !/function adminPlusOrderFlowStatus[\\s\\S]{0,700}marketplacePreparingAt/.test(app));
check("defined business flow", app.includes("AdminPlus <strong>입금전</strong>") && app.includes("AdminPlus <strong>주문접수</strong>") && app.includes("AdminPlus <strong>배송준비중</strong>") && app.includes("AdminPlus <strong>배송</strong>"));
console.log("[ROUND 3] confirmed link -> mapping source-of-truth migration");
check("mapping sync helper exists", app.includes("syncMappingsFromConfirmedAdminPlusLinks"));
check("confirmed vendor/product overwrites identity only", app.includes("vendorName = text(link.vendorName)") && app.includes("vendorCode = text(link.productCode)") && app.includes("vendorProductName = text(link.productName)"));
check("operational Excel values preserved", app.includes("optionId/baseQty/shippingFee/purchaseTime/cost는 엑셀 운영값을 그대로 보존"));
check("legacy confirmed links auto migrate", app.includes("V253 이전에 만들어진 확정 AdminPlus 링크") && app.includes("serverSynced.changed"));
check("automation payload uses synced mappings", (app.match(/mappings: syncMappingsFromConfirmedAdminPlusLinks\(mappings, adminplusProductLinks\)\.rows/g)||[]).length>=2);
console.log("[ROUND 4] regression guards");
check("V253 manual purchase marker retained", app.includes("v253-adminplus-flow-integration-20260817") && worker.includes("v253-adminplus-flow-integration-20260817"));
check("shipment marketplace transition logic retained separately", worker.includes("adminplusEnsureMarketplacePreparing") && worker.includes("marketplacePreparingAt"));
check("channel+option mapping key retained", app.includes('return `${parseChannel(row.channel)}|${cleanId(row.optionId)}`'));
if(failed){console.error(`\\n[FAIL] V254 verifier ${failed} checks failed.`);process.exit(1);} console.log("\\n[PASS] V254 AdminPlus source-of-truth verification completed.");
