import fs from "node:fs";
const app=fs.readFileSync("apps/web/src/App.tsx","utf8");
const worker=fs.readFileSync("apps/worker/src/worker.ts","utf8");
const pkg=JSON.parse(fs.readFileSync("package.json","utf8"));
let failed=0;
const check=(name,cond)=>{if(cond)console.log(`[PASS] ${name}`);else{console.error(`[FAIL] ${name}`);failed++;}};
console.log("[ROUND 1] status count integrity");
check("V257+ header", /const\s+UI_RELEASE_REVISION\s*=\s*["']V(?:25[7-9]|2[6-9]\d|[3-9]\d\d)["']/.test(app));
check("V257 web marker", app.includes('v257-status-range-count-fix-20260817'));
check("status queries no longer hardcode seven days", !app.includes('fetchOperationStatus(channel, status, 7)'));
check("shared selected date range passed to status API",
  /fetchOperationStatus\s*\(\s*channel\s*,\s*status\s*,\s*orderApiFilter\.startDate\s*,\s*orderApiFilter\.endDate\s*,?\s*\)/s.test(app)
);
check("Coupang explicit paging matches server diagnostic", app.includes('query.maxPerPage = 50') && app.includes('query.maxPages = 10'));
check("status API calls are sequential", app.includes('for (const [channel, status, bucket] of specs)') && !app.includes('Promise.allSettled(specs.map(([channel, status]) => fetchOperationStatus'));
check("API response counts retained", app.includes('rawRows: Number(result.summary?.rawRows') && app.includes('normalizedRows: Number(result.summary?.normalizedRows'));
check("partial query failure surfaced", app.includes('조회실패 ${failed}건'));
console.log("[ROUND 2] shared range UI");
const startBindings=(app.match(/value=\{orderApiFilter\.startDate\}/g)||[]).length;
const endBindings=(app.match(/value=\{orderApiFilter\.endDate\}/g)||[]).length;
check("today and automation share start date state", startBindings>=3);
check("today and automation share end date state", endBindings>=3);
check("today status toolbar has range UI", /api-overview-toolbar[\s\S]{0,1200}시작일[\s\S]{0,600}종료일[\s\S]{0,600}현황 새로고침/.test(app));
check("automation flow has range UI", /주문 진행상태 현황[\s\S]{0,1600}조회 시작일[\s\S]{0,600}조회 종료일[\s\S]{0,900}진행상태 새로고침/.test(app));
check("automation flow rows filtered by shared period", app.includes('.filter((row) => operationRangeIncludes(row.submittedAt || row.orderedAt))'));
console.log("[ROUND 3] regressions");
check("V256 manual mapping retained", app.includes('v256-manual-mapping-nonapi-transition-20260817') && worker.includes('v256-manual-mapping-nonapi-transition-20260817'));
check("V255 source-of-truth retained", app.includes('v255-adminplus-link-status-fix-20260817') && worker.includes('v255-adminplus-link-status-fix-20260817'));
check("verify all adds V257", String(pkg.scripts?.["verify:all"]||"").includes("verify:v257"));
if(failed){console.error(`\n[FAIL] V257 verifier ${failed} checks failed.`);process.exit(1);}console.log("\n[PASS] V257 status range/count verification completed.");
