import fs from "node:fs";
const worker=fs.readFileSync("apps/worker/src/worker.ts","utf8");
const app=fs.existsSync("apps/web/src/App.tsx")?fs.readFileSync("apps/web/src/App.tsx","utf8"):"";
const must=(ok,msg)=>{if(!ok)throw new Error(msg);console.log(`[PASS] ${msg}`)};
console.log("[ROUND 1] option-level single-active coupon guard");
must(worker.includes("couponAppliedOwnershipSnapshot"),"APPLIED ownership snapshot exists");
must(worker.includes("APPLIED 쿠폰/옵션 조회 실패로 중복 위험") && worker.includes('skipped: "applied_lookup_failed"'),"lookup failure never becomes zero-active");
must(worker.includes('skipped: "duplicate_active_coupon"'),"duplicate active option blocks new issue");
must(worker.includes('skipped: "already_active"'),"one active coupon prevents duplicate issue");
must(worker.includes("missingOptionIds") && worker.includes("활성쿠폰이 없던 옵션"),"only zero-active options are issued");
console.log("[ROUND 2] 30-second rollover + continuity");
must(worker.includes("lastCanceledAtIso") && worker.includes("30_000"),"verified cancellation has 30-second safety gate");
must(worker.includes('skipped: "post_cancel_30s_wait"'),"post-cancel issue waits at least 30 seconds");
must(worker.includes("저장된 cancel 상태가 아니라 쿠팡의 실제 APPLIED 옵션 소유관계"),"actual APPLIED state is final issue source");
must(worker.includes("활성 쿠폰이 없고 방금 종료된 건이 아니면 즉시 발행"),"zero-active option can self-heal immediately");
console.log("[ROUND 3] AdminPlus API product search filter / regression");
must(worker.includes("adminplusCatalogProductIsActiveUnlimited") && worker.includes('status === "active"') && worker.includes('stock === "unlimited"'),"backend active+unlimited filter exists");
must(worker.includes("activeUnlimitedOnly = body.activeUnlimitedOnly !== false"),"active+unlimited is default backend filter");
must(app.includes("adminplusGlobalSearchActiveUnlimitedOnly") && app.includes("active + unlimited만 보기"),"user can toggle API product search filter");
must(/const UI_RELEASE_REVISION = "V248 R8(?:\.\d+)?";/.test(app),"web UI R8 revision exposed");
must(worker.includes('couponSingleActiveRevision: "v248-r8-coupon-single-active-catalog-filter-20260813"'),"R8 runtime marker exposed");
must(worker.includes("v248-r7r1-receiver-phone-address2-relink-20260812"),"R7.1 shipment relink retained");
console.log("[PASS] V248 R8 coupon single-active + catalog filter verification completed (3 rounds).");
