import fs from "node:fs";
const worker=fs.readFileSync("apps/worker/src/worker.ts","utf8");
const app=fs.existsSync("apps/web/src/App.tsx")?fs.readFileSync("apps/web/src/App.tsx","utf8"):"";
const must=(ok,msg)=>{if(!ok)throw new Error(msg);console.log(`[PASS] ${msg}`)};
console.log("[ROUND 1] adaptive low-cost coupon monitoring");
must(worker.includes("couponAdaptiveHealthIntervalMs"),"adaptive health interval exists");
must(worker.includes("15 * 60_000") && worker.includes("5 * 60_000") && worker.includes("60_000"),"15m/5m/1m adaptive cadence exists");
must(worker.includes("nextCouponHealthCheckAtIso"),"next health check is persisted");
must(worker.includes("await sleepMs(350)"),"coupon item scans are rate-limit throttled");
console.log("[ROUND 2] actual-end + 30-second reissue safety");
must(worker.includes("inactiveObservedAtIso"),"actual inactive observation is persisted");
must(worker.includes('skipped: "inactive_observed_30s_wait"'),"30-second actual-inactive confirmation exists");
must(worker.includes("forceCouponExpireFor24hRollover = false"),"scheduled forced expiration is disabled");
must(worker.includes("startAt: kstDateTimeSecondText(start)") && worker.includes("24 * 60 * 60 * 1000"),"reissued coupon starts immediately and lasts 24h");
console.log("[ROUND 3] revision/regression/UI");
must(worker.includes('couponAdaptiveActualEndRevision: "v248-r8r3-adaptive-actual-end-reissue-20260813"'),"R8.3 runtime marker exposed");
must(worker.includes('couponSingleActiveRevision: "v248-r8-coupon-single-active-catalog-filter-20260813"'),"R8 single-active guard retained");
must(worker.includes('manualOrderSafeRelinkRevision: "v248-r7r1-receiver-phone-address2-relink-20260812"'),"R7.1 shipment relink retained");
if(app) must(/const UI_RELEASE_REVISION = "V248 R(?:8\.3|9(?:\.\d+)?)"/.test(app),"web UI revision exposed");
console.log("[PASS] V248 R8.3 adaptive actual-end reissue verification completed (3 rounds).");
