-- V187 coupon automation durable retry and failure notifications
-- V187 쿠폰 자동운영 재시도·실패 알림
create table if not exists public.coupon_automation_retries (
  id bigint generated by default as identity primary key,
  retry_key text not null unique,
  settings_key text not null default 'default',
  platform text not null default 'coupang',
  template_id text not null,
  stage text not null,
  attempt integer not null default 3,
  run_at timestamptz not null,
  status text not null default 'pending',
  payload jsonb not null default '{}'::jsonb,
  last_error text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_coupon_automation_retries_due
  on public.coupon_automation_retries (status, run_at);

create table if not exists public.coupon_automation_failures (
  id bigint generated by default as identity primary key,
  failure_key text not null unique,
  settings_key text not null default 'default',
  platform text not null default 'coupang',
  template_id text not null,
  coupon_id text not null default '',
  coupon_name text not null default '',
  stage text not null,
  status text not null default 'unacknowledged',
  attempt_count integer not null default 0,
  error_code text not null default '',
  error_message text not null default '',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  acknowledged_at timestamptz
);

create index if not exists idx_coupon_automation_failures_status
  on public.coupon_automation_failures (status, created_at desc);
