-- V60 서버운영 사전절차용 통합 Supabase 스키마
-- 신규 배포 시 이 파일 1개만 실행하면 됩니다.
-- 기존 V49~V59 사용자는 재실행해도 안전합니다.
-- operation_audit_logs는 서버 운영점검/수동 실행 기록 보관용입니다.

create table if not exists public.operation_temp_sessions (
  session_key text primary key,
  payload jsonb not null default '{}'::jsonb,
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);

create index if not exists idx_operation_temp_sessions_expires_at
  on public.operation_temp_sessions (expires_at);

create table if not exists public.operation_persistent_settings (
  settings_key text primary key,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_operation_persistent_settings_updated_at
  on public.operation_persistent_settings (updated_at desc);

create table if not exists public.operation_audit_logs (
  id bigint generated by default as identity primary key,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_operation_audit_logs_created_at
  on public.operation_audit_logs (created_at desc);
